### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by rrahmati** [johnarevalo/blocks-char-rnn#1]
When sampling, why do we need to provide seq_length characters as the input? Shouldn't it be one character at a time?

**Comment by johnarevalo** [comment]
You're right, `seq_length`-th sequences was the quick n' dirty way to keep the hidden states between each character. `predict` function should also receive initial hidden states as input. I'll update it.

**Comment by johnarevalo** [comment]
This commit works for `gru` and `rnn`. `lstm` layers require additional `cell_states` handling.

**Comment by rrahmati** [comment]
Works perfect. Thanks.
